### PR TITLE
Pyqt5

### PR DESCRIPTION
**Pull request by mkutu**
These changes will allow you to run the script from the Raspberry Pi 4 directly instead o having to use a laptop. Most changes are not on python scripts but will be on physical raspberry pi. Details in readme. You'll still need a monitor, mouse, and keyboard. This still needs further testing.
Najor changes include:
1. using miniforge (a conda env manager) to install arm64 only packages. Using virtualenv or other virtual environment managers will try and install amd64 packages that will break on install. This really only applies to PyQt.
2. installing Qt5 and pyqt5 on system 
3. changing imports PyQt6 to PyQt5. Everything else should be backwards compatible but still needs further testing
More info in README

HAS NOT BEEN TESTED ON BENCHBOT
ONLY BEEN TESTED ON PI and has successfully gotten the GUI to popup

### CODE REVIEW

**Comment by mkutu** [comment]
MAKE THIS A NEW BRANCH PLEASE

DO NOT MERGE WITH MASTER

This has not been tested on a working bbot, only on the Pi to get the Gui to pop-up. 

I didn't know how to create a pull request into a new branch without having permissions for this repo.

**Review by marialauracangiano — CHANGES_REQUESTED** [review]
We'll test PyQt5 and merge if it works.

**Comment by marialauracangiano** [comment]
It would be good to create a new folder with this version since the GUI.py here will always be different if you are using just a pi than if you are using a pi and a laptop. Unless I'm confused here and the version you have should work with any setup in which case we don't need the extra folder. I have you as a member of the repo so I'm not sure why you can't just create a new branch there. 

image

I would suggest:
1. Create a new branch from the dev
2. Create a new folder where you include the necessary files to setup your pi if the pi is your host. Or same folder if you think that your script will work with any setup. 
3. Once you've tested your scripts we can merge everything to the dev and main

**Comment by mkutu** [comment]
@marialauracangiano this is an old comment from when I was not a member of the repo.  

Thanks for your suggestions. I'm happy to do what you've suggested. But may I suggest an additional option? 

Using a configuration file helps resolve a lot of the "hard coded" constant through the code base, pretty much all of [these](https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/blob/27597d07f5dbd6f700b6048a32943d0dd9c45a01/Laptop%20setup/GUI/GUI.py#L52-L66) and it avoids having to manually enter env variable in the command line that you can't see. I think, @priyajakhar correct me if I'm wrong, this is what you're doing [here](https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/blob/27597d07f5dbd6f700b6048a32943d0dd9c45a01/Laptop%20setup/GUI/GUI.py#L27-L39). 

I'm suggesting doing something very similar, but instead of writing everything in the command line, create a separate file, `configuration.yaml`, that has all [this information](https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/blob/27597d07f5dbd6f700b6048a32943d0dd9c45a01/Laptop%20setup/GUI/GUI.py#L27-L66) in a single location and can be easily read by people (and your code) for debugging and changing. Then coordinating your scripts through a single `main.py` file.

There are various ways you can setup a your configuration. We use a tool called Hydra which is way overkill for this. But it uses a `.yaml` file which is very easy to read (unlike a json dictionary or command line variable inputs). A `main.py` makes things more _object-oriented_ which is a system design paradigm that breaks things into smaller pieces thus making them easier to debug. Debugging i think is a primary focus since we are, and will be in future, integrating multiple pieces of hard-ware and software across various user-levels.

Option 2:
1. Create a single configuration file that keep all your hard-coded variables, plus an option to run with RPi or with a laptop, in a single location.
2. Make a `main.py` script that coordinates your overall system including `GUI.py`  and pull the configuration file into that `main.py`.
 
Some pseudo code would look something like this:

## config.yaml

```YAML
ROBOT_LENGTH: some number
ROBOT_WIDTH: some number
PI_USERNAME: your username
PI_PASSWORD: your password
DISTANCE_TRAVELED: some number
WHEEL_MOTORS: some numbers
NUMBER_OF_SENSORS: some number
# and 
SETUP_TYPE: RPi  # or Laptop

```

## main.py
```Python
# main.py
import GUI
import sensor_server
import yaml

with open('config.yaml') as f:
    config = yaml.load(f, Loader=yaml.FullLoader)

ROBOT_LENGTH =config["ROBOT_LENGTH "]
# width of the robot (distance between two front wheels) in cm
ROBOT_WIDTH = config["ROBOT_WIDTH "]
# if you haven't changed your pi's name the default username is 'pi'
PI_USERNAME = config["PI_USERNAME "]
# if you haven't changed your pi's password, the default is 'raspberrypi'
PI_PASSWORD = config["PI_PASSWORD "]
# Distance between rows in mm
DISTANCE_TRAVELED = int(config["DISTANCE_TRAVELED "]])
# if BB moving backwards change the motors order to [3,2]
WHEEL_MOTORS = list(map(int,config["WHEEL_MOTORS "].split(',')))
# number of ultrasonic sensors on the robot
NUMBER_OF_SENSORS = int(config["NUMBER_OF_SENSORS "])

# and
SETUP_TYPE = config["setup_type"]

if SETUP_TYPE  == "RPi":
    start sensor server
    """(make slight tweaks in GUI that allow for 2 different setups. This is as simple as a single if/else statement. 2 lines of code.)"""
    start GUI 
    
if SETUP_TYPE  == "Laptop":
    start GUI (same)
    Do other stuff that's needed for laptop setup

```

**Comment by marialauracangiano** [comment]
Regarding the question of the  "hard coded" constants. Each site should have a .env file where these variables are stored, as we have it setup now, since these vary per site. The .env file looks a lot like the config.yaml file that you are suggesting (I don't have one in my laptop but Jack can share ours with you as an example). Could you explain what the differences would be between those two? In principle they seem to fulfill the same purpose.
I agree about having everything in one main file and being able to switch depending on SETUP_TYPE.

**Comment by mkutu** [comment]
> @marialauracangiano this is an old comment from when I was not a member of the repo.
> 
> Thanks for your suggestions. I'm happy to do what you've suggested. But may I suggest an additional option?
> 
> Using a configuration file helps resolve a lot of the "hard coded" constant through the code base, pretty much all of [these](https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/blob/27597d07f5dbd6f700b6048a32943d0dd9c45a01/Laptop%20setup/GUI/GUI.py#L52-L66) and it avoids having to manually enter env variable in the command line that you can't see. I think, @priyajakhar correct me if I'm wrong, this is what you're doing [here](https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/blob/27597d07f5dbd6f700b6048a32943d0dd9c45a01/Laptop%20setup/GUI/GUI.py#L27-L39).
> 
> I'm suggesting doing something very similar, but instead of writing everything in the command line, create a separate file, `configuration.yaml`, that has all [this information](https://github.com/precision-sustainable-ag/BenchBot-SonyHRCam/blob/27597d07f5dbd6f700b6048a32943d0dd9c45a01/Laptop%20setup/GUI/GUI.py#L27-L66) in a single location and can be easily read by people (and your code) for debugging and changing. Then coordinating your scripts through a single `main.py` file.
> 
> There are various ways you can setup a your configuration. We use a tool called Hydra which is way overkill for this. But it uses a `.yaml` file which is very easy to read (unlike a json dictionary or command line variable inputs). A `main.py` makes things more _object-oriented_ which is a system design paradigm that breaks things into smaller pieces thus making them easier to debug. Debugging i think is a primary focus since we are, and will be in future, integrating multiple pieces of hard-ware and software across various user-levels.
> 
> Option 2:
> 
>     1. Create a single configuration file that keep all your hard-coded variables, plus an option to run with RPi or with a laptop, in a single location.
> 
>     2. Make a `main.py` script that coordinates your overall system including `GUI.py`  and pull the configuration file into that `main.py`.
> 
> 
> Some pseudo code would look something like this:
> ## config.yaml
> 
> ```yaml
> ROBOT_LENGTH: some number
> ROBOT_WIDTH: some number
> PI_USERNAME: your username
> PI_PASSWORD: your password
> DISTANCE_TRAVELED: some number
> WHEEL_MOTORS: some numbers
> NUMBER_OF_SENSORS: some number
> # and 
> SETUP_TYPE: RPi  # or Laptop
> ```
> 
> ## main.py
> 
> ```python
> # main.py
> import GUI
> import sensor_server
> import yaml
> 
> with open('config.yaml') as f:
>     config = yaml.load(f, Loader=yaml.FullLoader)
> 
> ROBOT_LENGTH =config["ROBOT_LENGTH "]
> # width of the robot (distance between two front wheels) in cm
> ROBOT_WIDTH = config["ROBOT_WIDTH "]
> # if you haven't changed your pi's name the default username is 'pi'
> PI_USERNAME = config["PI_USERNAME "]
> # if you haven't changed your pi's password, the default is 'raspberrypi'
> PI_PASSWORD = config["PI_PASSWORD "]
> # Distance between rows in mm
> DISTANCE_TRAVELED = int(config["DISTANCE_TRAVELED "]])
> # if BB moving backwards change the motors order to [3,2]
> WHEEL_MOTORS = list(map(int,config["WHEEL_MOTORS "].split(',')))
> # number of ultrasonic sensors on the robot
> NUMBER_OF_SENSORS = int(config["NUMBER_OF_SENSORS "])
> 
> # and
> SETUP_TYPE = config["setup_type"]
> 
> if SETUP_TYPE  == "RPi":
>     start sensor server
>     """(make slight tweaks in GUI that allow for 2 different setups. This is as simple as a single if/else statement. 2 lines of code.)"""
>     start GUI 
>     
> if SETUP_TYPE  == "Laptop":
>     start GUI (same)
>     Do other stuff that's needed for laptop setup
> ```

**Comment by mkutu** [comment]
oops accidently closed

**Pull request closed without merging**
